### ISSUE TITLE
[BUG]🐛 images are not loading

### ISSUE THREAD

**Issue by vishaldev21** [tithi-deb/Resume-Building-Website-CVAST#6]
The image paths in all HTML files are incorrect.

**Comment by Sohini3018** [comment]
@Vishal21121 Actually I have already fixed it and made a PR #7 regarding that. Thanks for your help! Meanwhile, can you check for the responsiveness in the mobile view?

**Comment by vishaldev21** [comment]
It appears that this issue has already been addressed. Therefore, I will proceed to close it.
